rvm:
  - 1.8.7
  - 1.9.2
gemfile:
  - test/gemfiles/Gemfile.rails-2.0.x
  - test/gemfiles/Gemfile.rails-2.1.x
  - test/gemfiles/Gemfile.rails-2.2.x
  - test/gemfiles/Gemfile.rails-2.3.x
  - test/gemfiles/Gemfile.rails-xss-2.3.x
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
matrix:
  exclude:
    - { rvm: 1.9.2, gemfile: test/gemfiles/Gemfile.rails-2.0.x }
    - { rvm: 1.9.2, gemfile: test/gemfiles/Gemfile.rails-2.1.x }
    - { rvm: 1.9.2, gemfile: test/gemfiles/Gemfile.rails-2.2.x }
branches:
  only:
    - master
    - stable
script: "bundle exec rake submodules test"
