rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
matrix:
  exclude:
    # Don't kill Travis: just test against the latest version on JRuby and rbx.
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }

    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }

    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }

  allow_failures:
    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.2.x }

branches:
  only:
    - master
    - stable
script: "bundle exec rake submodules test"
