sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - jruby-9.1.12.0
  - rbx-3
gemfile:
  - test/gemfiles/Gemfile.rails-5.1.x
  - test/gemfiles/Gemfile.rails-5.0.x
  - test/gemfiles/Gemfile.rails-5.0.x.erubi
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.0.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: test/gemfiles/Gemfile.rails-5.0.x.erubi
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x.erubi
    - rvm: 2.4.1
      gemfile: test/gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.4.1
      gemfile: test/gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.4.1
      gemfile: test/gemfiles/Gemfile.rails-4.2.x
  include:
    - rvm: 2.4.1
      gemfile: test/gemfiles/Gemfile.rails-edge
  allow_failures:
    - rvm: rbx-3
    - gemfile: test/gemfiles/Gemfile.rails-edge
  fast_finish: true
script: "bundle exec rake submodules test"
